name: AdaTest
favicon: null
layout_spectrum: 0.79247
typography_spectrum: 0.83978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
