name: AdaTest
favicon: null
layout_spectrum: 0.06332816812209785
typography_spectrum: 0.7465412721503526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06610096362419426
  lightness: 0.7326391134411097
  saturation: 0.436217324109748
  rhythmicContrast: 0.9417037079110742
purpose: []
